### PR TITLE
[fanuc_lrmate200id_support] Set joint effort for LRMate200iD

### PR DESCRIPTION
**Pull request by wkentaro**
- Based on http://www.fanuc.co.jp/en/product/catalog/pdf/robot/LRMate200iD(E)_v04.pdf.
- This is necessary to control robot on Gazebo simulator.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
I appreciate the contribution, but I rather doubt that the maximum effort is equal to the _allowable load moment_, which is also defined _at the wrist_ only. At least, I think you used the `16.6Nm` figure from there, correct?

Are you sure this is the correct data?

**Comment by gavanderhoorn** [comment]
Also: I've only needed to set the effort limits for things like effort based controllers. Have you looked at the position based controllers in `ros_control` / `gazebo_ros_control`? They wouldn't need these limits.

**Comment by wkentaro** [comment]
> I appreciate the contribution, but I rather doubt that the maximum effort is equal to the allowable load moment, which is also defined at the wrist only. At least, I think you used the 16.6Nm figure from there, correct?

Yes, I used that value.

> Are you sure this is the correct data?

Actually, I don't have the real robot and no. I used it just a reference.

**Comment by wkentaro** [comment]
> Also: I've only needed to set the effort limits for things like effort based controllers. Have you looked at the position based controllers in ros_control / gazebo_ros_control? They wouldn't need these limits.

Thanks. I changed the configuration to use **position control**: #20

**Pull request closed without merging**
