### PR TITLE
Add support for R-2000iC/210F

### PR DESCRIPTION
**Pull request by Didier-Surface**
I added support for R2000iC /210F version. 

It is my first PR so let me know if I need to change something.
And if there is any test I have to make to check that this support package works with the hardware.

I won't take much credit as this version is the same with the /165F (done by @marip8 ) with only changes for joint max velocities in the URDF.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Thanks for the PR, appreciated.

> [..] this version is the same with the /165F (done by @marip8 ) with only changes for joint max velocities in the URDF.

if that's the case, then I believe we'd only need a new `_macro.xacro` and `.xacro` and some changes to the manifest and build script, correct?

The meshes could be reused from the `/165F`.

Could you update the PR to reuse as much as possible from that variant?

As the kinematics are identical as well, the OPW parameters could also be reused.

The joint names `.yaml` should stay, as well as the `.launch` and test files.

**Review by gavanderhoorn — CHANGES_REQUESTED** [review]
Marking as changes-requested so we don't accidentally merge.

**Comment by Didier-Surface** [comment]
By same as /165F, I mean that every file related to the /210F version in the support package is a copy of its equivalent for the /165F and I only replaced the 165f to 210f occurrence inside the file or in the file name.
The meshes are the same as for the /165f, but I changed the name.
The OPW yaml file is also identical with the name changed to 210F.
And indeed, only the .xacro and _macro.xacro files have more difference than just name/occurrence change.

Although they are the same, I thought it would be better to keep the versions distinct, in case someone wants to use without having to keep the /165F version around, or in case we discover that some files actually need further modifications away from the /165F version in the future.

Let me know if I made the wrong assumption, and I will update the PR.

I did change the CMakeLists.txt, but not the packages.xml file, as I was not sure I should do it.

**Comment by gavanderhoorn** [comment]
> By same as /165F, I mean that every file related to the /210F version in the support package is a copy of its equivalent for the /165F and I only replaced the 165f to 210f occurrence inside the file or in the file name.

yes, I'd understood that.

> The meshes are the same as for the /165f, but I changed the name.
> The OPW yaml file is also identical with the name changed to 210F.
> And indeed, only the .xacro and _macro.xacro files have more difference than just name/occurrence change.

Great.

> Although they are the same, I thought it would be better to keep the versions distinct, in case someone wants to use without having to keep the /165F version around, 

that would mean they'd have to delete the files from this package, which is not something that is often done.

Deleting "unneeded packages" does sometimes happen (although it's better to use the white/blacklisting feature of the build tools in almost all cases), but removing variant support from a single package seems unlikely.

> or in case we discover that some files actually need further modifications away from the /165F version in the future.

If that happens, in the future, we can then decide to duplicate the files and modify the copies, or come up with some approach.

Let's not keep duplicates around which take up space and bloat the repository unnecessarily.

> I did change the CMakeLists.txt, but not the packages.xml file, as I was not sure I should do it.

The manifest should mention the added variant, similar to how the other variants are mentioned.

> Let me know if I made the wrong assumption, and I will update the PR.

it would be great if you could avoid/reduce duplication of files as much as possible.

**Comment by Didier-Surface** [comment]
Thanks for the detailed answer. It was the wrong assumption indeed and made me realize that I actually use the tools wrongly.
I will make the change during the day

**Comment by Didier-Surface** [comment]
Changes have been made. I removed the mesh file and the OPW parameters file, modified both CMakeLists and package.xml and updated the _macro.xacro file. I left test and launch files as well as the joint names .yaml files.

I have 2 questions though:
- the joint names .yaml files content is the same for all versions. What is the rationale of keeping one file per variant?
- Should we notify somewhere that OPW parameters are the same for /210F and /165F?

**Comment by gavanderhoorn** [comment]
> * the joint names .yaml files content is the same for all versions. What is the rationale of keeping one file per variant?

it's a bit of a trade-off: they are very small, so duplication isn't really an issue like it would be with meshes, and it keeps things simpler than if we'd start reusing everything possible between variants.

ROS is complex enough as it is, and support packages can become really complex (with `xacro` supporting loading data from `.yaml` files fi, macros calling each other, recursive model generation, etc). To balance this a bit, we opt(ed) to not complicate things further by allowing some duplication in places where it doesn't really affect either package size or maintenance.

So it's true the contents is identical to other variants, but the file is part of the standard files for each supported variant and you'll need to provide a custom one as soon as you start creating more complex composite workcells (as you'd need to ensure unique joint names then).

> * Should we notify somewhere that OPW parameters are the same for /210F and /165F?

Yes, we should, and in fact we should mention also that the `/210F` variant uses the meshes from the `/165` as "*they are identical apart from the joint limits and some other characteristics we don't model right now*".

We typically add a note like this to the manifest, like in the LR Mate200iD support package:

https://github.com/ros-industrial/fanuc_experimental/blob/55a95feab9905d725f4499d3e15523d51749b8c9/fanuc_lrmate200id_support/package.xml#L11-L15

**Comment by Didier-Surface** [comment]
I understand.
Just to be sure:
> We typically add a note like this to the manifest, like in the LR Mate200iD support package:

Should I make the note or is it the maintainer's role? (happy to do it, but since it is my first PR, I don't want to overstep where I should not)

**Comment by gavanderhoorn** [comment]
I'll add the notice in the appropriate place(s).

thanks for the PR already.

I'll do a complete review sometime later.

**Review by gavanderhoorn — APPROVED** [review]
All seems OK.

I've added the notice to the manifest.

Thanks for the PR :+1:

**Comment by gavanderhoorn** [comment]
Thanks again :+1: 

I've squashed merged this, so the fixups don't end up in the history.

You may want to remove the branch manually, if GH doesn't offer you to do it.

**Comment by Didier-Surface** [comment]
Happy to help. Thanks for taking care of this

**Pull request merged**
