### PR TITLE
Improve collision mesh of axis 3

### PR DESCRIPTION
**Pull request by VictorLamoine**
The collision mesh of the third axis really is too coarse; collisions are detected where the robot is clear from colliding.

This improves the mesh without adding a single vertex (I've done some simplification on other faces).

anim

Should I modify the visual mesh as well?

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Yes, I didn't like them when I created them, and you're right, especially `link_3` is way too 'blobby'.

This looks like a much better approximation, thanks.

re: visual mesh: yes, please do, they should essentially just be the same (so a copy would be fine).

could you rebase on `indigo-devel` also please?

**Comment by VictorLamoine** [comment]
Done.

I tried [B-Spline](http://www.pointclouds.org/documentation/tutorials/bspline_fitting.php#bspline-fitting) fitting on a sampled point cloud (created from the visual model) but it's not good at all, so I can't think of an automatic solution for producing better meshes!

capture du 2015-10-28 13 51 40

**Comment by gavanderhoorn** [comment]
Thanks.

Yeah, that doesn't look too good :).

**Comment by gavanderhoorn** [comment]
I've been eyeing [V-HACD](http://kmamou.blogspot.ca/2014/11/v-hacd-v20-is-here.html) as a possible way to do this, but haven't had time to evaluate it properly.

**Comment by gavanderhoorn** [comment]
Played with it a little:

sshot

Not bad for an automated tool.

**Comment by VictorLamoine** [comment]
Too good! You could probably even reverse-engineer the robot with these aha!
It's integrated into MeshLab?

**Comment by gavanderhoorn** [comment]
> Too good! You could probably even reverse-engineer the robot with these aha!

well, there are a lot of knobs to play with, resolution can probably be turned down even more.

But I'd say this is blobby enough. If you can reverse engineer a robot from this, you can probably make a lot of money.

> It's integrated into MeshLab?

No, I just opened the `.wrl` in it.

**Pull request merged**
