### PR TITLE
R2000ic 210l support

### PR DESCRIPTION
**Pull request by demorise**
@gavanderhoorn 
fanuc_2000ic_210l

Test results:

tf_echo
teach_pendant_tf

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Thanks for the PR.

The commit history seems a bit strange though: the second commit seems to delete all files related to the CRX-10iA/L, which were added by the first commit.

Was that what you intended to do?

**Comment by demorise** [comment]
> Thanks for the PR.
> 
> The commit history seems a bit strange though: the second commit seems to delete all files related to the CRX-10iA/L, which were added by the first commit.
> 
> Was that what you intended to do?

Yes, I was trying to separate the two PRs since the CRX-10iA/L PR was yet to be merged. If you prefer that I include both commits in one PR, I can do that.

**Comment by gavanderhoorn** [comment]
The easiest way to go about this would be if the /210L branch would not have the `crx10ial_support` branch as "parent", but it would be a branch off of `melodic-devel`. Seeing as the two support packages have nothing shared between them, that would have been possible.

In your current PR, ac123a8 physically *removes* the CRX-10iA/L files which were added in 0fcfd937.

If I were to merge this PR, in its current state, I'd effectively reverse #67.

That's not what we want.

Seeing as I've not reviewed this PR, and it's only a single commit right now, I'd suggest creating a new branch (off of `melodic-devel`), adding the new package, committing it, and then submitting a PR from that new branch.

Alternatively, you could re-add the CRX-10iA/L files to your local clone, update ac123a8 to include them and then `force-push`. That may be more involved though.

**Comment by demorise** [comment]
Closing because it has been replaced by #70

**Pull request closed without merging**
