### PR TITLE
Update lrmate200id link_2 collision mesh. Fixes #34.

### LINKED ISSUE #34: Collision meshes of LR 200id too restrictive.
The current collision meshes of the LR mate 200id are too restrictive.
In particular, I'm talking about the mesh for link2.
Link 2 is supposed to have a bigger opening such that link 4 is partly inside of the current link 2 collision mesh (example of such a joint configuration in radians: [0, 0.3, -1, 0, 1.3, 0]).

### PR DESCRIPTION
**Pull request by jettan**
As suggested by @gavanderhoorn, I used the bounding-mesh application with outer bounding box algorithm and reduced some STL model I had available to 2000 vertices.

Also, fixes #34 as mentioned in the commit message itself.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Thanks.

I'll take a look.

**Comment by gavanderhoorn** [comment]
Btw: I know the current meshes also aren't very pretty, but the results of those bounding mesh algorithms really look nasty.

**Comment by jettan** [comment]
Glad I wasn't the only one who thought that.

**Comment by gavanderhoorn** [comment]
It's not the nicest mesh, but it's better than what we have now, so this will do.

Thanks @jettan, and my apologies for taking so long to merge this.

**Pull request merged**
