### PR TITLE
Add Fanuc M710iC/45M

### PR DESCRIPTION
**Pull request by VictorLamoine**
The differences with the M710iC/50 are the longer link 2 and link 4 and reduced payload.

# Technical drawing
m710ic45m

# Screenshots
screenshot_20190122_144359

Not included in this pull request (but I can provide the meshes privately).
screenshot_20190122_144352

Compared to the M710iC/50 I have updated only link 2 and link 4 meshes for collisions, I've used MeshLab convex hull function (QHull).

### CODE REVIEW

**Comment by VictorLamoine** [comment]
Tests are failing ,I'll fix that soon

**Comment by gavanderhoorn** [comment]
Travis uses Indigo, so Jade+ xacro extensions are not enabled by default. I expect things to work if you'd add `--inorder`.

**Comment by VictorLamoine** [comment]
We're good

**Comment by VictorLamoine** [comment]
Friendly pi(n)g :pig2:

**Review by gavanderhoorn — CHANGES_REQUESTED** [review]
Overall this looks quite ok. :+1: for the PR.

Seeing as you already notice this yourself:

> Compared to the M710iC/50 I have updated only link 2 and link 4 meshes for collisions

could you perhaps check whether there is opportunity to reuse the meshes of the `/50` in this variant? That would avoid adding duplicates of all the other meshes to the new variant's `mesh` directory.

You could either refer to the `meshes/m710ic50` directory from the `_macro.xacro` of the M-710iC/45M, or create a `common` sub dir under `meshes` to store the common meshes and make both `_macro.xacro`s use that.

**Comment by gavanderhoorn** [comment]
I've pushed a few minor commits to your feature branch directly. Saves me from having to ask you to fix those things.

**Comment by VictorLamoine** [comment]
Yes it usually takes less time to do these small modifications than ask other people to do them :)

**Comment by VictorLamoine** [comment]
I have added a comment on top the `xacro` file saying we re-use the meshes from the M710iC45M. I kept the meshes of the M710iC45M in their original directory

I would have gone with symbolic links but it is not portable on Microsoft Windows so you probably won't like it.

**Review by gavanderhoorn — APPROVED** [review]
Looks ok now. I'm going to wait on Travis and then merge.

**Comment by VictorLamoine** [comment]
@gavanderhoorn Travis passed, thank you

**Comment by gavanderhoorn** [comment]
Thanks for the PR @VictorLamoine :+1: 

appreciated.

**Pull request merged**
