### PR TITLE
Import R-2000iC/270F variant from harissuwig

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

@harissuwig: as you didn't have issues enabled on your fork, I took the liberty of preparing a PR with the commit which adds the variant to the support package.

I'd be interested in merging it here in `fanuc_experimental`, but wanted to reach out to your first.

Note: I've only included the initial commit from your `r2000ic270f` branch, as I'm not too keen on maintaining MoveIt configurations here.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Note: I've not tested this yet with RG.

**Comment by gavanderhoorn** [comment]
I might merge this after testing it with RG.

@harissuwig licensed the package in his fork BSD, which would permit reuse of the files under the same license terms.

**Comment by harissuwig** [comment]
Hi @gavanderhoorn, thank you for reaching out

Yes you can merge it if you want to, glad that I can help

**Comment by gavanderhoorn** [comment]
transforms seem to ligne up with what RG tells me, so I believe this model is OK to merge.

Thanks @harissuwig :+1:

**Pull request merged**
