### PR TITLE
lrmate200id_gazebo_demo: Gazebo demonstration of reactive planning: Touch the floor

### PR DESCRIPTION
**Pull request by wkentaro**
## Summary

In reactive planning, the robot detect the force from floor and stops the execution of trajectory.
### **NOT** Reactive

```
roslaunch fanuc_lrmate200id_gazebo_demo touch_the_floor.launch reactive:=false
```

https://drive.google.com/open?id=0B9P1L--7Wd2vLVlsZnNJcWtfSkU
### Reactive

```
roslaunch fanuc_lrmate200id_gazebo_demo touch_the_floor.launch reactive:=true
```

https://drive.google.com/open?id=0B9P1L--7Wd2vSVRqSnVpX19iQmc

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@wkentaro: this PR is included in #25. Would it be ok to close this one?

In any case I'd like to suggest the same thing as I did in https://github.com/ros-industrial/fanuc_experimental/pull/25#issuecomment-243446209.

**Comment by gavanderhoorn** [comment]
@wkentaro: :bell: ?

**Comment by wkentaro** [comment]
@gavanderhoorn Ok to close this.

**Comment by gavanderhoorn** [comment]
Closing, as discussed.

**Pull request closed without merging**
